### ISSUE TITLE
BE | Implement text search

### ISSUE THREAD

**Issue by AnaGrskovic** [Tubicor/Interaction-Map-Project#48]
Idea: text search doesn't remove what was filtered with other filters just orders them by similarity?

**Comment by Tubicor** [comment]
For me the following happens when using
1. If only text is given it returns all results from the database
{
  "text": "sometextthatisnowhereindatabase"
}
3. If i added one item of any category audience it will return results from the database as if it ignores the text -> all results with that audience are returned
{
  "text": "sometextthatisnowhereindatabase",
  "audiences": [
    "55bc3bb7-3b5d-49e0-a62f-27a705ec84ac"
  ]
}

**Comment by AnaGrskovic** [comment]
So it's a misunderstanding, just as i thought 
The text search is a field for sorting, while the other fields are used for filtering.
That means that all of the professionals that would otherwise be included in the result are included regardless of the text search. Text search is only used to order the professionals by their similarity to the text search. The professionals who share the most words with the text search will appear first in the response, while the ones with less or no shared words appear later. 
If you think that would be better, i can also implement it in a way that the results with zero shared words arent included at all.
